# Generated by Django 2.2.12 on 2021-08-17 19:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20210817_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tag'),
        ),
    ]
