# Generated by Django 2.2.12 on 2021-08-19 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20210820_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_dislikes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_or_dislike',
            field=models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_dislikes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
