# Generated by Django 2.2.12 on 2021-08-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20210820_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
